# Generated by Django 3.2.9 on 2021-11-19 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='adrress_complement',
            new_name='address_complement',
        ),
    ]
