# Generated by Django 3.2.9 on 2021-11-19 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0002_rename_adrress_complement_user_address_complement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address_complement',
            field=models.CharField(max_length=60, verbose_name='Address Complement'),
        ),
    ]
