# Generated by Django 3.2.9 on 2021-11-23 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0003_alter_user_address_complement'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='num_changed_books',
            field=models.IntegerField(default=0, verbose_name='Num changed books'),
        ),
    ]
